
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.srs.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.srsNP.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.clh3.RData")

 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh3p.05_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh3p.07_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh3p.09_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh3p.11_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh3p.05_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh3p.07_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh3p.09_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh3p.11_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh5p.05_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh5p.07_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh5p.09_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh5p.11_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh5p.05_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh5p.07_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh5p.09_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.indh5p.11_v2.RData")

 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3p.05_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3p.07_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3p.09_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3p.11_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3p.05_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3p.07_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3p.09_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3p.11_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3h5p.05_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3h5p.07_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3h5p.09_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3h5p.11_v1.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3h5p.05_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3h5p.07_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3h5p.09_v2.RData")
 load("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\ed.bothh3h5p.11_v2.RData")
 
 save.image("D:\\Dropbox\\Mumu\\Research New\\Data example\\HPC Mar7 Edu Rimage\\all.ed.RData")